name: Build and Upload VowelCountApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version you need

      - name: Build the project
        run: dotnet build source/VowelCountApp/

      - name: Zip the output
        run: |
          mkdir output
          cp -r source/VowelCountApp/bin/Debug/net8.0/* output/  # Adjust the path as necessary
          zip -r output.zip output/

      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: VowelCountApp-output
          path: output.zip
